ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: check-added-large-files
  - id: debug-statements
  - id: name-tests-test
  - id: sort-simple-yaml

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.23.3
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.4
  hooks:
  - id: ruff # linter
    args: [--fix, --exit-non-zero-on-fix, --show-fixes]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
  - id: mypy
    additional_dependencies:
    - types-requests
