### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-nubank

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox and test dependencies
      run: |
        pip install tox -r requirements-test.txt
    - name: Test with pytest
      run: |
        tox -e python${{ matrix.python-version }}
